### PR TITLE
Create ThirdRealitySmartBlind.groovy

### PR DESCRIPTION
**Pull request by weihuan1111**
create third reality smart blind

### CODE REVIEW

**Review by weihuan1111 — COMMENTED** [review]
create thirdreality smart blind

**Comment by weihuan1111** [comment]
@MikeMaxwell can you help to review the merge request, thanks

**Comment by weihuan1111** [comment]
@bravenel can you help to review the merge request, thanks

**Comment by bravenel** [comment]
We don’t do merge requests to our public repo.  

You need to find somewhere else to publish this.

**Comment by weihuan1111** [comment]
@bravenel Do you know where I should post the code to make our device usable on hubatat

**Comment by weihuan1111** [comment]
@bravenel Do you know where I should post the code to make our device usable on hubitat

**Comment by bravenel** [comment]
Put them in a public github repo, and post at community.hubitat.com <http://community.hubitat.com/>

**Pull request closed without merging**
